# Arithmetic-TASK
Please create a method (in the class) that depends on what value it gets as an argument throws an ArithmeticException or
ArrayIndexOutBoundsException or it will not throw any exception.
Each of the above exceptions is to be handled by a separate clause catch, we additionally put a finally clause in the code that informs user that it is finally block happend.
Everything should be run in a separate class with the main() method.
